### ISSUE TITLE
Deployment user in Nexus 3

### ISSUE THREAD

**Issue by paulvi** [sonatype/nexus-book-examples#22]
https://help.sonatype.com/display/NXRM3/Maven+Repositories#MavenRepositories-ConfiguringApacheMaven shows to directly using `admin` account for deployment, that is bad practice from security point of view, as `admin` account can be used to login and change Nexus server configuration.

```
<settings>
....
  <servers>
    <server>
      <id>nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
  </servers>
```

This is step backward from Nexus 2, where there was special user `deployment`
https://stackoverflow.com/questions/6950346/infrastructure-with-maven-jenkins-nexus

Is there better way to do in Nexus 3?

**Comment by paulvi** [comment]
Docs a bit differ:
in https://help.sonatype.com/display/NXRM3/Post+Install+Checklist Step 4 is 
> The deployment user’s password defaults to deployment123. Change this password

While https://help.sonatype.com/display/NXRM3/Users says
> The repository manager ships with two users by default: admin and anonymous.

**Comment by joedragons** [comment]
@paulvi Sorry for the delay in reply.  As you state, NXRM3 only comes with 2 users out of the box.  There is always the ability to add more however we made a conscious decision not to limit it to those two in NXRM3.  If you liked the deployment user in NXRM2, you should be able to recreate it (or when you upgrade from NXRM2 to 3 it should come over).
The usage of admin/admin123 is just an example.  You would substitute whatever user had whatever permissions you needed.
This is the first request I can recall for restoration of the deployment user in the default NXRM3 install.  If you wish it to be returned, you can file an issue on issues.sonatype.com however I can tell you IMO it's very unlikely we'll do it unless there's both high demand and good reason, since as noted it was a conscious decision to remove.
Hope that helps.

**Comment by paulvi** [comment]
In short:

there should be 'deployment' user,  
and the documentation should not promote writing all-mighty `admin` password in config files.
